# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'linux-x64'

stages:
  - stage: BuildAndPublish
    displayName: Build and Push Docket to Register then Publish of release pipeline
    jobs:
    - job: Build
      steps:
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          containerRegistry: 'nmpersonalregistry'
          repository: 'CustomerManagement'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'